### ISSUE TITLE
In team members ranking the "total number of votes" is providing figures across all teams

### ISSUE THREAD

**Issue by Vallicek** [vince-from-nice/flexygames#10]
TO VERIFY

Go in stats
Go in orange labs team (but I think bug is with all teams)
     NB: Bravo for the new interface, clearer
Select "total number of votes" + "all sessions groups"

expected behaviour: I expect figures for orange labs team for all its sessions

current behaviour: Figures cross all teams (I do not think that sylvain AF and loudo have so much votes for so few participations):

1    User avatar     sylvainAF  110,00
2    User avatar     AoA    87,00
3    User avatar     Jeremie    73,00
4    User avatar     karson_nice    67,00
5    User avatar     RFL    66,00
6    User avatar     yann06 61,00
7    User avatar     Loudo  53,00

**Comment by vince-from-nice** [comment]
Yes it was a real bug but it is fixed now .
