### ISSUE TITLE
Provide HTTPS at least for the user authentification

### ISSUE THREAD

**Issue by monsieurp** [vince-from-nice/flexygames#11]
As it stands, flexygames does NOT provide a way to encrypt my data via HTTPS. When logging in, since no encryption mechanism is currently provided, passwords can be sniffed through the network fairly easily.

The HTTPS protocol should be offered as a way to browse the website.

Please either generate a self-signed certificate or buy one.

**Comment by vince-from-nice** [comment]
Yes you're right, FG needs HTTPS at least for the authentification.

**Comment by monsieurp** [comment]
Mec tu vas le créer ce certificat HTTPS ou je vais te tacler à la gorge ?

**Comment by vince-from-nice** [comment]
Tout de suite la violence !

**Comment by vince-from-nice** [comment]
Sinon en attendant je mette du HTTPS, t'as qu'à te mettre un mdp bidon (comme toi).

**Comment by vince-from-nice** [comment]
Ok c'est implémenté, merci Mister P pour m'avoir fait découvrir https://letsencrypt.org.

Il y a désormais une redirection pour TOUT mettre vers HTTPS, mais le top serait de continuer à fournir en HTTP les ressources statiques genre les images mais bon c'est du fignolage...
