### ISSUE TITLE
 "Envoyer à tous les participants disponibles ou acceptés" est aussi envoyé à d'autres statuts

### ISSUE THREAD

**Issue by Vallicek** [vince-from-nice/flexygames#12]
Le message personnalise "Envoyer à tous les participants disponibles ou acceptés" est aussi envoye a d autres statuts, ex: liste d attente

Fait: http://www.flexygames.net/sessions/show/175230
14 acceptes, 9 forfaits, 6 listes d attente, "Nombre de joueurs disponibles : 20 / 90 (14 sont acceptés)"
MAIS:
"Mail has been sent to 20 participant(s)."

**Comment by vince-from-nice** [comment]
Le bug est corrigé mais il faudrait carrément améliorer le truc en proposant par exemple la liste des statuts afin de choisir son filtre...
