### ISSUE TITLE
In user statistics page the value of "votes" by session group is wrong

### ISSUE THREAD

**Issue by Vallicek** [vince-from-nice/flexygames#14]
in http://www.flexygames.net/player/stats/15624
I have 12 votes for

Championnat de foot ASIE d'AirFrance (2015/2016) (SérieD2) 3   3   0 (0%)  0 (0%)  3 (100%)    1   0,33    0,33    12

When I click on it to have details, I have only 6 votes: http://www.flexygames.net/player/stats/15624?groupId=147593

**Comment by vince-from-nice** [comment]
The bug has been fixed, thanks for the reporting.

FYI it was concerning the team members ranking page too !
