### ISSUE TITLE
Display the locking time of sessions

### ISSUE THREAD

**Issue by Vallicek** [vince-from-nice/flexygames#15]
Indiquer en clair en debut de session l heure limite d inscription 

heure limite d inscription = heure de debut - parametre de groupe de session

**Comment by vince-from-nice** [comment]
Done in 2s, thanks to Groovy !!

**Comment by Vallicek** [comment]
Bravo. Le texte "Vérrouillage de la session" est trop technique. Lui preferer: "heure l imite d inscription", il faut designer le site comme si c etait ta mere qui l utilisais

**Comment by vince-from-nice** [comment]
Un tooltip expliquant la date de verrouillage est maintenant affiché.
