### ISSUE TITLE
Les stats des joueurs "match par match" ne sont plus affichées

### ISSUE THREAD

**Issue by Vallicek** [vince-from-nice/flexygames#17]
un bug:

Sur
http://www.flexygames.net/player/show/15624
les colonnes
Date    Équipe Groupe  Statut
somt remplies

pas les colonnes
Victoires   Nuls    Défaites   actions Votes

**Comment by vince-from-nice** [comment]
Effectivement, et ça concernait également les statistiques détaillées par groupe de sessions (ex: http://www.flexygames.net/player/stats/15624?groupId=148157).

Mais je parle à l'imparfait car le bug a été corrigé hier soir ! ;)
