### ISSUE TITLE
Tableaux avec possibilité de classement

### ISSUE THREAD

**Issue by Vallicek** [vince-from-nice/flexygames#3]
Changer l objet duquel heritent tous les tableaux utilises dans Flexy (en particulier le tableau des joueurs dans une session):
utiliser un objet generique qui laisse de petites icones de classement dans chaque colonne (du + petit au plus grand ET classement decroissant), comme dans excel, outlook, ou beaucoup de pages Wikipedia

**Comment by vince-from-nice** [comment]
Je pense plus que ça soit vraiment nécessaire maintenant que le tri par défaut du tableau des participants est _intelligent_ (disons moins bête plutôt):
- les participants sont d'abord regroupés par leur statut
- ils sont ensuite triés par leur nom sauf pour le statut Disponible où là ils sont triés par date (de la dernière mise à jour)
