### ISSUE TITLE
Mouseover bug in team members pie chart (statistics page)

### ISSUE THREAD

**Issue by Vallicek** [vince-from-nice/flexygames#9]
There is a display bug: in http://www.flexygames.net/site/stats DOWN

Put your mouse on the legend, any of the team. The team name is too short, so a mouseover appears, but it is in maority hidden by a white box. See hereunder:

![image](https://cloud.githubusercontent.com/assets/16670386/12554594/926ae2ca-c37d-11e5-9395-c5acc15497e1.png)

**Comment by vince-from-nice** [comment]
You're right, I need to fix it.. but it will be simplier and better to display directly the full name of the teams in the pie chart legend !

**Comment by vince-from-nice** [comment]
I have changed a little bit the layout of pie chart and it is much better now ! :)

I also have to make clickable the user columns or team/group slices, but we can consider this "bug" as closed.

**Comment by Vallicek** [comment]
this page has disappeared... see http://www.flexygames.net/site/stats

**Comment by vince-from-nice** [comment]
In fact it has been fixed around 8:00 AM.  You are really a morning person !!
